/*
 * The MIT License
 *
 * Copyright 2017 Denis Karev.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package tictactoe.game;
import java.awt.*;
/**
 *
 * @author Денис
 */
public class PlayField extends javax.swing.JFrame {

    int[][] playField; //игровое поле, восприяте компьютера
    boolean isCross = true; //крестики ходят первыми
    int i; //для очистки переменных
    MainMenu menu = new MainMenu();
    /**
     * Creates new form PlayField
     */
    public PlayField() {
        playField = new int[3][3];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos00 = new javax.swing.JTextField();
        pos01 = new javax.swing.JTextField();
        pos02 = new javax.swing.JTextField();
        pos10 = new javax.swing.JTextField();
        pos11 = new javax.swing.JTextField();
        pos12 = new javax.swing.JTextField();
        pos20 = new javax.swing.JTextField();
        pos21 = new javax.swing.JTextField();
        pos22 = new javax.swing.JTextField();
        info = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pos00.setEditable(false);
        pos00.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos00.setToolTipText("");
        pos00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos00MouseClicked(evt);
            }
        });

        pos01.setEditable(false);
        pos01.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos01.setToolTipText("");
        pos01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos01MouseClicked(evt);
            }
        });

        pos02.setEditable(false);
        pos02.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos02.setToolTipText("");
        pos02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos02MouseClicked(evt);
            }
        });

        pos10.setEditable(false);
        pos10.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos10.setToolTipText("");
        pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos10MouseClicked(evt);
            }
        });

        pos11.setEditable(false);
        pos11.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos11.setToolTipText("");
        pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos11MouseClicked(evt);
            }
        });

        pos12.setEditable(false);
        pos12.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos12.setToolTipText("");
        pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos12MouseClicked(evt);
            }
        });

        pos20.setEditable(false);
        pos20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos20.setToolTipText("");
        pos20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos20MouseClicked(evt);
            }
        });

        pos21.setEditable(false);
        pos21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos21.setToolTipText("");
        pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos21MouseClicked(evt);
            }
        });

        pos22.setEditable(false);
        pos22.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        pos22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos22.setToolTipText("");
        pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos22MouseClicked(evt);
            }
        });

        info.setEditable(false);
        info.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N

        clearButton.setText("Очистить");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Выйти");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(info)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(closeButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos00MouseClicked
        if (isCross == true) {
           switch(playField[0][0]) {
               case 0: 
                   pos00.setText("X");
                   pos00.setForeground(Color.blue);
                   playField[0][0] = 1;
                   info.setText("Крестики сходили [1:1]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
           
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[0][0]) {
                case 0:
                    pos00.setText("O");
                    pos00.setForeground(Color.red);
                    playField[0][0] = 2;
                    info.setText("Нолики сходили [1:1]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos00MouseClicked

    private void pos01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos01MouseClicked
        if (isCross == true) {
           switch(playField[0][1]) {
               case 0: 
                   pos01.setText("X");
                   pos01.setForeground(Color.blue);                   
                   playField[0][1] = 1;
                   info.setText("Крестики сходили [1:2]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[0][1]) {
                case 0:
                    pos01.setText("O");
                    pos01.setForeground(Color.red);                    
                    playField[0][1] = 2;
                    info.setText("Нолики сходили [1:2]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos01MouseClicked

    private void pos02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos02MouseClicked
        if (isCross == true) {
           switch(playField[0][2]) {
               case 0: 
                   pos02.setText("X");
                   pos02.setForeground(Color.blue);
                   playField[0][2] = 1;
                   info.setText("Крестики сходили [1:3]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[0][2]) {
                case 0:
                    pos02.setText("O");
                    pos02.setForeground(Color.red);                    
                    playField[0][2] = 2;
                    info.setText("Нолики сходили [1:3]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos02MouseClicked

    private void pos10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos10MouseClicked
       if (isCross == true) {
           switch(playField[1][0]) {
               case 0: 
                   pos10.setText("X");
                   pos10.setForeground(Color.blue);                   
                   playField[1][0] = 1;
                   info.setText("Крестики сходили [2:1]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[1][0]) {
                case 0:
                    pos10.setText("O");
                    pos10.setForeground(Color.red);                    
                    playField[1][0] = 2;
                    info.setText("Нолики сходили [2:1]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos10MouseClicked

    private void pos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos11MouseClicked
       if (isCross == true) {
           switch(playField[1][1]) {
               case 0: 
                   pos11.setText("X");
                   pos11.setForeground(Color.blue);                   
                   playField[1][1] = 1;
                   info.setText("Крестики сходили [2:2]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[1][1]) {
                case 0:
                    pos11.setText("O");
                    pos11.setForeground(Color.red);
                    playField[1][1] = 2;
                    info.setText("Нолики сходили [2:2]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos11MouseClicked

    private void pos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos12MouseClicked
       if (isCross == true) {
           switch(playField[1][2]) {
               case 0: 
                   pos12.setText("X");
                   pos12.setForeground(Color.blue);                   
                   playField[1][2] = 1;
                   info.setText("Крестики сходили [2:3]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[1][2]) {
                case 0:
                    pos12.setText("O");
                    pos12.setForeground(Color.red);
                    playField[1][2] = 2;
                    info.setText("Нолики сходили [2:3]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos12MouseClicked

    private void pos20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos20MouseClicked
       if (isCross == true) {
           switch(playField[2][0]) {
               case 0: 
                   pos20.setText("X");
                   pos20.setForeground(Color.blue);                   
                   playField[2][0] = 1;
                   info.setText("Крестики сходили [3:1]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[2][0]) {
                case 0:
                    pos20.setText("O");
                    pos20.setForeground(Color.red);                    
                    playField[2][0] = 2;
                    info.setText("Нолики сходили [3:1]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos20MouseClicked

    private void pos21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos21MouseClicked
       if (isCross == true) {
           switch(playField[2][1]) {
               case 0: 
                   pos21.setText("X");
                   pos21.setForeground(Color.blue);                   
                   playField[2][1] = 1;
                   info.setText("Крестики сходили [3:2]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           } 
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[2][1]) {
                case 0:
                    pos21.setText("O");
                    pos21.setForeground(Color.red);                    
                    playField[2][1] = 2;
                    info.setText("Нолики сходили [3:2]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos21MouseClicked

    private void pos22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos22MouseClicked
       if (isCross == true) {
           switch(playField[2][2]) {
               case 0: 
                   pos22.setText("X");
                   pos22.setForeground(Color.blue);                   
                   playField[2][2] = 1;
                   info.setText("Крестики сходили [3:3]. Ход ноликов!");
                   isCross = false;
                   break;
               default: 
                   info.setText("Невозможно соверишть такой ход!");
                   break;
           }
                      
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[2][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        } else {
            switch (playField[2][2]) {
                case 0:
                    pos22.setText("O");
                    pos22.setForeground(Color.red);
                    playField[2][2] = 2;
                    info.setText("Нолики сходили [3:3]. Ход крестиков!");
                    isCross = true;
                    break;
                default:
                    info.setText("Невозможно совершить такой ход!");
            }
                       
           if ( //условия победы КРЕСТИКОВ
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 1))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 1))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 1))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 1))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 1))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 1))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 1))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 1))    
               ) {
                    info.setText("Крестики побеждают!");
           } else if 
               (
               ((playField[0][0] == playField[0][1]) && (playField[0][0] == playField[0][2]) && (playField[0][0] == 2))//горизонтали
                   ||
               ((playField[1][0] == playField[1][1]) && (playField[1][0] == playField[1][2]) && (playField[1][0] == 2))
                   ||
               ((playField[2][0] == playField[2][1]) && (playField[2][0] == playField[2][2]) && (playField[2][0] == 2))
                   ||
               ((playField[0][0] == playField[1][0]) && (playField[0][0] == playField[2][0]) && (playField[0][0] == 2))//вертикали   
                   ||
               ((playField[0][1] == playField[1][1]) && (playField[0][1] == playField[2][1]) && (playField[0][1] == 2))    
                   ||
               ((playField[0][2] == playField[1][2]) && (playField[0][2] == playField[2][2]) && (playField[0][2] == 2))
                   ||
               ((playField[0][0] == playField[1][1]) && (playField[0][0] == playField[1][2]) && (playField[0][0] == 2))//диагонали    
                   ||
               ((playField[0][2] == playField[1][1]) && (playField[0][2] == playField[2][0]) && (playField[0][2] == 2))  
               ) {
                   info.setText("Нолики побеждают!");
           } else if
               ((playField[0][0] != 0) && (playField[0][1] != 0) && (playField[0][2] != 0) && (playField[1][0] != 0) && (playField[1][1] != 0) && 
                   (playField[1][2] != 0) && (playField[2][0] != 0) && (playField[2][1] != 0) && (playField[2][2] != 0)) {
                   info.setText("Ничья!");
           }
           
        }
    }//GEN-LAST:event_pos22MouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        pos00.setText("");
        pos01.setText("");
        pos02.setText("");
        pos10.setText("");
        pos11.setText("");
        pos12.setText("");
        pos20.setText("");
        pos21.setText("");
        pos22.setText("");
        playField[0][0] = 0;
        playField[0][1] = 0;
        playField[0][2] = 0;
        playField[1][0] = 0;
        playField[1][1] = 0;
        playField[1][2] = 0;
        playField[2][0] = 0;
        playField[2][1] = 0;
        playField[2][2] = 0;
        info.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField info;
    private javax.swing.JTextField pos00;
    private javax.swing.JTextField pos01;
    private javax.swing.JTextField pos02;
    private javax.swing.JTextField pos10;
    private javax.swing.JTextField pos11;
    private javax.swing.JTextField pos12;
    private javax.swing.JTextField pos20;
    private javax.swing.JTextField pos21;
    private javax.swing.JTextField pos22;
    // End of variables declaration//GEN-END:variables
}